### ISSUE TITLE
Multiple domains for one server?

### ISSUE THREAD

**Issue by MaximFiedler** [LabyMod/server-media#608]
Is it possible to have multiple domains for a single server? For instance, if I were to use the .de domain for my server instead of .net, there would be no HD icon and banner. If not, perhaps the option could be added to the manifest.json.

I have another question: How are the people behind the pull request verified? Anyone could open a pull request to change a server's logo or something, but what if it's not even their server?

**Comment by scrummer** [comment]
Hi
thank you for the request.

First: You can add server wildcards in the manifest.json of your server in addition to the main domain. See: https://github.com/LabyMod/server-media/blob/master/docs/Manifest.md#available-keys

Second: Yes you are absolutely right. Everyone could open PRs and change something. But this is how open source works. This is publicly visible to everyone and every change can also be reviewed by everyone. This is comparable to the question: "Isn't open source software more insecure, since hackers could just view the code and check it for vulnerabilities?" -> Yes, everyone can see and change it but every change is reviewed by staff and community and everything can be backtracked to the person who changed it. So just changing something to bullshit is never a good move in OpenSource. The bad guy is always the looser.
Also: We know the larger servers good enough to see if PRs are valid or not and check certain important stuff that is submitted/changed in a PR.

Hope this helps

Best,
Scrummer

**Comment by scrummer** [comment]
Feel free to open a new issue or reopen this one if you got further questions! 

~Scrummer
