### ISSUE TITLE
Wildcards Not Updated ?

### ISSUE THREAD

**Issue by Koldskal** [LabyMod/server-media#955]
When will your server be added to Laby.net and visible on the Server List?

**Comment by MeHaVr** [comment]
My to

**Comment by Fedox-die-Ente** [comment]
Mine too

**Comment by jvstinxz** [comment]
same here

**Comment by Tamikaschu** [comment]
Same here. We have been waiting for one week now

**Comment by Fedox-die-Ente** [comment]
Someone has a solution?

**Comment by MeHaVr** [comment]
I'm waiting 3 weeks now

**Comment by Fedox-die-Ente** [comment]
@JakobBruening

**Comment by Fedox-die-Ente** [comment]
@DoJapHD

**Comment by JakobBruening** [comment]
Hey! Same answer as in the other issue:

Unfortunately, there was an issue in checking for new servers. Due to another issue with wildcards (you also noticed it here) the whole publish script needed to be changed in base structure. And due to other important tasks and the complexity, it was not possible to implement a fix that fast. Sorry for the late feedback here in the issue.

However, every server should now exist correctly in laby.net. And everything should work in the feature without any problems! Thank you for waiting.
If there are still any issues, feel free to address them here!

BR Jakob
