### ISSUE TITLE
Complete commit does not changed?

### ISSUE THREAD

**Issue by gamingcodedev** [LabyMod/server-media#988]
Hey you have merged some code from me, to your main branch but the changes haven't applied yet on laby.net, could someone tell me why?

**Comment by Tamikaschu** [comment]
Our pr was merged 20 days ago. The Update still hasn't applied to Laby.net. I think u might have to wait as well.

**Comment by Fedox-die-Ente** [comment]
> Our pr was merged 20 days ago. The Update still hasn't applied to Laby.net. I think u might have to wait as well.

Well i asked support and the answer was "We are working on it."

**Comment by JakobBruening** [comment]
> Well i asked support and the answer was "We are working on it."

That's actually true. Unfortunately, there was an issue in checking for new servers. Due to another issue with wildcards (see #955) the whole publish script needed to be changed in base structure. And due to other important tasks and the complexity, it was not possible to implement a fix that fast. Sorry for the late feedback here in the issue.

However, every server should now exists correctly in laby.net. Thank you for waiting.
If there are still any problems, feel free to address them here!

BR Jakob
